### ISSUE TITLE
Add CDN support

### ISSUE THREAD

**Issue by patogordo** [bayssmekanique/vue-click#25]

**Comment by nerdoza** [comment]
Hello @PatoGordo,

The library is available from the [**JSDELIVR**](https://www.jsdelivr.com/) and [**UNPKG**](https://unpkg.com/) CDNs and it's using [**UMD**](https://github.com/umdjs/umd#readme) so it's ready to use in the browser.

To use it in your application from a CDN, add a script tag to import the script and it will be available in the global scope as `VueClick` (though you will have to use the `default` property for installation).

Example:
```html
<script src="https://unpkg.com/vue@next"></script>
<script src="https://unpkg.com/vue-click@latest"></script>
<script>
  const app = Vue.createApp({/* App Config */})
  app.use(VueClick.default)
  app.mount('#app')
</script>
```

Thank you for bringing this to my attention. I will add a portion to the [`README.md`](https://github.com/bayssmekanique/vue-click#cdn) file to explain this for future users!
